baseurl: ""
url: "http://goals.nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
yandex_metrika: 38534700
google_analytics: UA-46456269-17

title: "Николай Воробьёв"
description: "Научу достигать целей легко и с удовольствием"
keywords: "Клуб личностного роста"
author: "Николай Воробьёв"

permalink: /:title/
